jdk: oraclejdk8
language: android

android:
  components:
    # Using latest platform tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-27"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

script: ./gradlew lint test

deploy:
  - provider: script
    script: ./gradlew gitPublishPush
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ./gradlew gitPublishPush
    skip_cleanup: true
    on:
      branch: master

notifications:
  email: false
  slack:
    secure: j44+p22Ys8pRlVW7SGBeE/EgLZN+RqednyYzdDf8ca5mNNKKQ9Ro6H7uKNzpPhPAbb3wtUwoOOhYCkRd3mVJNlN8HeVs6u6Ypzz+OBeSRmYesGl0ct1W1BQxNe+RLxBiM9bASVoe93rSa3M2T0BfNA/UvuK5moQDe8z116UA6M3Hhb9x1uNY1mWLTAZG8o/jWP7rde+ab6Z0JtYFSAFxCoE9z8mNe+qPrdCXTX2opewhkm2jMg5YfZi0lXxLG2LEnQDwe+HB6EAHVS9+g2xWhEtDAUVh0K8DRBehD1x6ptXMS1Sjv715+NLr+ZcQAyqcoJXjimYrFdxVYSztAG4E8oj1zQeks4zt+L1bvm2UsX7qq8u2wdySWEEL9udBR30oIRIEjn60C8hhJBUmlmMi9yqDmfMXkYvI8p8vaAWybjWArNeFJNsNSrPCNcm4sQszEifh7iNJdWfKJS76AAoOpMq1nrKYMP4xwI0L+0hr3pv0w762ug+l7M9ENGXZLUleMED4BmcE1G86zSqdY3PS9FPfSNCWWXKaWQ9DJY8H5Kfp483yE5ILUPtF2ZTKcGwbjrhyWaOVIlGVMc/SBL1CapfUdVZWSt6RrE7Zh/o4tAhds32K1/CtZH6xL9YC644KZb37OCh8A+Sre9092M5taLl9S9xGOr9GstJSV+sQ/7U=
