jdk: oraclejdk8
language: android

android:
  components:
    # Using latest platform tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-27"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

script: ./gradlew lint test

deploy:
  - provider: script
    script: ./gradlew gitPublishPush
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ./gradlew gitPublishPush
    skip_cleanup: true
    on:
      branch: master

notifications:
  email: false
  slack:
    secure: hkxZl7Sl/QrtibJQjSBgLZI7PMDJbDEmQM0GdC7x+9T88L62aNhS18YfgXbeGkqpmLj0AG2NsaY8JqVKuq/gF5Vge/1S/z8E+j/oBy1t0ru5WvX1dnrzGY066dAdgwskXZncGOKbZ1JNwgmOAk/Cg17ZxwpCd/uZp9csDumGVv2v7u1oCcORoyzQgmCa+qlSkM/E3vit0sDRtbhxSQGgu2XaXBNUFxx1lU2+x+1kOfXOw5VcDc6eGeJWozK7xiRl/2PLX960s2kcE01IowgjQ25NR+bTCUMYZhq9RXLebcnA2s8DBtki7Z9qIT3UOADggKZFOWY4f4HpUB9moGfFboHHuvU1Lf+B3Gt4QHDbwmz4zCcKaTUtiNSewP5qgYSDjZTwToH1ysGEM11OMilu7X+fczmCRhxgJcSlvVZAieC9RiAHF8kFOUYowlM5flPKuonpIlLbO0nO9PQvzdArlVvO6yrE85TCxk1oMG6D/ceQtQOQRetZsn+EmZC4Qp+izY2SJdMnLedqTP7wqfHY3J0uOw8WJ9Km9iqu1Tqt9PoBSYlhwcyBljz3DtD7j0/xNbgjYoPCZaGZ6XiXO4Dtig0blPQpsy9sqlcAZUJ5Q+3Gm2+l8eMQmu8eWsD9uQTQkGFgOPiSLxXtULDaBxdBiTuMKoaew+y1aJ3oaV/nZR0=
